### ISSUE TITLE
:hover gets removed on closing "Custom CSS" section

### ISSUE THREAD

**Issue by michael-mass** [Codeinwp/gutenberg-css#118]
Whenever the "Custom CSS" section is closed, my ":hover" keyword disappears.

For example, if my CSS is:
`selector:hover {
opacity: 50%;
}`

When I close the section, the ":hover" keyword is no longer there:
`selector {
opacity: 50%;
}`

It's more of an annoyance since it seems like the ":hover" affect still works, but if I open the "Custom CSS" section again to change something, I MUST add the ":hover" keyword back or it will stop working.

**Comment by HardeepAsrani** [comment]
@michaelmass90 Update to the latest version, it's been fixed. :)
