### ISSUE TITLE
CSS module causing Section and other blocks to fail after publishing

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/gutenberg-css#298]
It's a weird issue and I've no idea why this might be happening. This is one of the posts where this is happening: https://pastebin.com/UuHUy5uH - make sure you also install the Ultimate Gutenberg plugin so those blocks work..but the issue has nothing to do with their plugin.

Can you help and see if you're able to reproduce this? @Soare-Robert-Daniel @irinelenache

**Comment by Soare-Robert-Daniel** [comment]
@HardeepAsrani, for the *Preview* in the `Network` tab on the browser inspector, I can not see their CSS file loaded. Their components have no CSS.
![image](https://user-images.githubusercontent.com/17597852/120972940-f545e900-c776-11eb-932f-46e3f339b394.png)

In the editor, these are the CSS properties that they need to have in the frontend.
![image](https://user-images.githubusercontent.com/17597852/120973192-4b1a9100-c777-11eb-92ce-b745b8259b0f.png)

The thing is when the article is published, everything seems to be normal.
![image](https://user-images.githubusercontent.com/17597852/120973584-caa86000-c777-11eb-9cd3-84dce9f615a1.png)

Also, I spotted a weird CSS name class on their blocks: `uagb-section__background-undefined`

**Comment by irinelenache** [comment]
I couldn't replicate it, it works fine for me after publishing

**Comment by HardeepAsrani** [comment]
@Soare-Robert-Daniel Can you reproduce it on Jurassic Ninja or tastewp so I could check?

**Comment by Soare-Robert-Daniel** [comment]
I could not reproduce the issue in Jurassic Ninja, also even in my local environment, the problem on the *Preview* has been solved.
