### ISSUE TITLE
"Prepare for WordPress 5.3" commit broke package.json file

### ISSUE THREAD

**Issue by brettshumaker** [Codeinwp/gutenberg-css#8]
The a4971980991ffe3bebdfde9d9c8448b085c30303 commit looks to have been a search/replace for a version string related to this plugin but inadvertently changed the version of the `css-loader` version string in `package.json` to a value that doesn't exist for that package: `1.0.2`

**Comment by HardeepAsrani** [comment]
Yea, weird how css-loader in package got updated with it. :) I've merged that PR.
